//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs18
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Маршрут.
    /// </summary>
    // *** Start programmer edit section *** (Маршрут CustomAttributes)

    // *** End programmer edit section *** (Маршрут CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МаршрутE", new string[] {
            "НомерМаршрута as \'Номер маршрута\'",
            "КонечПункт as \'Конечный пункт\'",
            "ВремяОтправ as \'Время отправления\'",
            "ВремяПрибыт as \'Время прибытия\'",
            "Стоимость as \'Стоимость\'",
            "Перевозчик as \'Наименование\'"})]
    [MasterViewDefineAttribute("МаршрутE", "Перевозчик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("МаршрутL", new string[] {
            "НомерМаршрута as \'Номер маршрута\'",
            "КонечПункт as \'Конечный пункт\'",
            "ВремяОтправ as \'Время отправления\'",
            "ВремяПрибыт as \'Время прибытия\'",
            "Стоимость as \'Стоимость\'",
            "Перевозчик as \'Наименование\'"})]
    [MasterViewDefineAttribute("МаршрутL", "Перевозчик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Маршрут : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерМаршрута;
        
        private int fСтоимость;
        
        private string fВремяОтправ;
        
        private string fВремяПрибыт;
        
        private string fКонечПункт;
        
        private IIS.Kyrs18.Перевозчик fПеревозчик;
        
        // *** Start programmer edit section *** (Маршрут CustomMembers)

        // *** End programmer edit section *** (Маршрут CustomMembers)

        
        /// <summary>
        /// ВремяОтправ.
        /// </summary>
        // *** Start programmer edit section *** (Маршрут.ВремяОтправ CustomAttributes)

        // *** End programmer edit section *** (Маршрут.ВремяОтправ CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОтправ
        {
            get
            {
                // *** Start programmer edit section *** (Маршрут.ВремяОтправ Get start)

                // *** End programmer edit section *** (Маршрут.ВремяОтправ Get start)
                string result = this.fВремяОтправ;
                // *** Start programmer edit section *** (Маршрут.ВремяОтправ Get end)

                // *** End programmer edit section *** (Маршрут.ВремяОтправ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маршрут.ВремяОтправ Set start)

                // *** End programmer edit section *** (Маршрут.ВремяОтправ Set start)
                this.fВремяОтправ = value;
                // *** Start programmer edit section *** (Маршрут.ВремяОтправ Set end)

                // *** End programmer edit section *** (Маршрут.ВремяОтправ Set end)
            }
        }
        
        /// <summary>
        /// ВремяПрибыт.
        /// </summary>
        // *** Start programmer edit section *** (Маршрут.ВремяПрибыт CustomAttributes)

        // *** End programmer edit section *** (Маршрут.ВремяПрибыт CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПрибыт
        {
            get
            {
                // *** Start programmer edit section *** (Маршрут.ВремяПрибыт Get start)

                // *** End programmer edit section *** (Маршрут.ВремяПрибыт Get start)
                string result = this.fВремяПрибыт;
                // *** Start programmer edit section *** (Маршрут.ВремяПрибыт Get end)

                // *** End programmer edit section *** (Маршрут.ВремяПрибыт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маршрут.ВремяПрибыт Set start)

                // *** End programmer edit section *** (Маршрут.ВремяПрибыт Set start)
                this.fВремяПрибыт = value;
                // *** Start programmer edit section *** (Маршрут.ВремяПрибыт Set end)

                // *** End programmer edit section *** (Маршрут.ВремяПрибыт Set end)
            }
        }
        
        /// <summary>
        /// КонечПункт.
        /// </summary>
        // *** Start programmer edit section *** (Маршрут.КонечПункт CustomAttributes)

        // *** End programmer edit section *** (Маршрут.КонечПункт CustomAttributes)
        [StrLen(255)]
        public virtual string КонечПункт
        {
            get
            {
                // *** Start programmer edit section *** (Маршрут.КонечПункт Get start)

                // *** End programmer edit section *** (Маршрут.КонечПункт Get start)
                string result = this.fКонечПункт;
                // *** Start programmer edit section *** (Маршрут.КонечПункт Get end)

                // *** End programmer edit section *** (Маршрут.КонечПункт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маршрут.КонечПункт Set start)

                // *** End programmer edit section *** (Маршрут.КонечПункт Set start)
                this.fКонечПункт = value;
                // *** Start programmer edit section *** (Маршрут.КонечПункт Set end)

                // *** End programmer edit section *** (Маршрут.КонечПункт Set end)
            }
        }
        
        /// <summary>
        /// НомерМаршрута.
        /// </summary>
        // *** Start programmer edit section *** (Маршрут.НомерМаршрута CustomAttributes)

        // *** End programmer edit section *** (Маршрут.НомерМаршрута CustomAttributes)
        public virtual int НомерМаршрута
        {
            get
            {
                // *** Start programmer edit section *** (Маршрут.НомерМаршрута Get start)

                // *** End programmer edit section *** (Маршрут.НомерМаршрута Get start)
                int result = this.fНомерМаршрута;
                // *** Start programmer edit section *** (Маршрут.НомерМаршрута Get end)

                // *** End programmer edit section *** (Маршрут.НомерМаршрута Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маршрут.НомерМаршрута Set start)

                // *** End programmer edit section *** (Маршрут.НомерМаршрута Set start)
                this.fНомерМаршрута = value;
                // *** Start programmer edit section *** (Маршрут.НомерМаршрута Set end)

                // *** End programmer edit section *** (Маршрут.НомерМаршрута Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Маршрут.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Маршрут.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Маршрут.Стоимость Get start)

                // *** End programmer edit section *** (Маршрут.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Маршрут.Стоимость Get end)

                // *** End programmer edit section *** (Маршрут.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маршрут.Стоимость Set start)

                // *** End programmer edit section *** (Маршрут.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Маршрут.Стоимость Set end)

                // *** End programmer edit section *** (Маршрут.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Маршрут.
        /// </summary>
        // *** Start programmer edit section *** (Маршрут.Перевозчик CustomAttributes)

        // *** End programmer edit section *** (Маршрут.Перевозчик CustomAttributes)
        [PropertyStorage(new string[] {
                "Перевозчик"})]
        [NotNull()]
        public virtual IIS.Kyrs18.Перевозчик Перевозчик
        {
            get
            {
                // *** Start programmer edit section *** (Маршрут.Перевозчик Get start)

                // *** End programmer edit section *** (Маршрут.Перевозчик Get start)
                IIS.Kyrs18.Перевозчик result = this.fПеревозчик;
                // *** Start programmer edit section *** (Маршрут.Перевозчик Get end)

                // *** End programmer edit section *** (Маршрут.Перевозчик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Маршрут.Перевозчик Set start)

                // *** End programmer edit section *** (Маршрут.Перевозчик Set start)
                this.fПеревозчик = value;
                // *** Start programmer edit section *** (Маршрут.Перевозчик Set end)

                // *** End programmer edit section *** (Маршрут.Перевозчик Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МаршрутE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МаршрутE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МаршрутE", typeof(IIS.Kyrs18.Маршрут));
                }
            }
            
            /// <summary>
            /// "МаршрутL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МаршрутL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МаршрутL", typeof(IIS.Kyrs18.Маршрут));
                }
            }
        }
    }
}
