//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs18
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обслуживание.
    /// </summary>
    // *** Start programmer edit section *** (Обслуживание CustomAttributes)

    // *** End programmer edit section *** (Обслуживание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбслуживаниеE", new string[] {
            "Оператор as \'Оператор\'",
            "БилетКасса as \'Наименование\'",
            "БилетКасса.Адрес as \'Адрес\'",
            "ВремяПроверки as \'Время проверки\'",
            "ЧекЛента as \'Чек лента\'",
            "ГотовКРаботе as \'Готов к работе\'"})]
    [MasterViewDefineAttribute("ОбслуживаниеE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбслуживаниеE", "БилетКасса", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ОбслуживаниеL", new string[] {
            "Оператор as \'ФИО\'",
            "БилетКасса as \'Наименование\'",
            "БилетКасса.Адрес as \'Адрес\'",
            "ВремяПроверки as \'Время проверки\'",
            "ЧекЛента as \'Чек лента\'",
            "ГотовКРаботе as \'Готов к работе\'"})]
    [MasterViewDefineAttribute("ОбслуживаниеL", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ОбслуживаниеL", "БилетКасса", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Обслуживание : ICSSoft.STORMNET.DataObject
    {
        
        private string fВремяПроверки;
        
        private bool fЧекЛента;
        
        private bool fГотовКРаботе;
        
        private IIS.Kyrs18.Оператор fОператор;
        
        private IIS.Kyrs18.БилетКасса fБилетКасса;
        
        // *** Start programmer edit section *** (Обслуживание CustomMembers)

        // *** End programmer edit section *** (Обслуживание CustomMembers)

        
        /// <summary>
        /// ВремяПроверки.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ВремяПроверки CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ВремяПроверки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПроверки
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Get start)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Get start)
                string result = this.fВремяПроверки;
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Get end)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Set start)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Set start)
                this.fВремяПроверки = value;
                // *** Start programmer edit section *** (Обслуживание.ВремяПроверки Set end)

                // *** End programmer edit section *** (Обслуживание.ВремяПроверки Set end)
            }
        }
        
        /// <summary>
        /// ГотовКРаботе.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ГотовКРаботе CustomAttributes)
        public virtual bool ГотовКРаботе
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Get start)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Get start)
                bool result = this.fГотовКРаботе;
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Get end)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Set start)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Set start)
                this.fГотовКРаботе = value;
                // *** Start programmer edit section *** (Обслуживание.ГотовКРаботе Set end)

                // *** End programmer edit section *** (Обслуживание.ГотовКРаботе Set end)
            }
        }
        
        /// <summary>
        /// ЧекЛента.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.ЧекЛента CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.ЧекЛента CustomAttributes)
        public virtual bool ЧекЛента
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.ЧекЛента Get start)

                // *** End programmer edit section *** (Обслуживание.ЧекЛента Get start)
                bool result = this.fЧекЛента;
                // *** Start programmer edit section *** (Обслуживание.ЧекЛента Get end)

                // *** End programmer edit section *** (Обслуживание.ЧекЛента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.ЧекЛента Set start)

                // *** End programmer edit section *** (Обслуживание.ЧекЛента Set start)
                this.fЧекЛента = value;
                // *** Start programmer edit section *** (Обслуживание.ЧекЛента Set end)

                // *** End programmer edit section *** (Обслуживание.ЧекЛента Set end)
            }
        }
        
        /// <summary>
        /// Обслуживание.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.БилетКасса CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.БилетКасса CustomAttributes)
        [PropertyStorage(new string[] {
                "БилетКасса"})]
        [NotNull()]
        public virtual IIS.Kyrs18.БилетКасса БилетКасса
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.БилетКасса Get start)

                // *** End programmer edit section *** (Обслуживание.БилетКасса Get start)
                IIS.Kyrs18.БилетКасса result = this.fБилетКасса;
                // *** Start programmer edit section *** (Обслуживание.БилетКасса Get end)

                // *** End programmer edit section *** (Обслуживание.БилетКасса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.БилетКасса Set start)

                // *** End programmer edit section *** (Обслуживание.БилетКасса Set start)
                this.fБилетКасса = value;
                // *** Start programmer edit section *** (Обслуживание.БилетКасса Set end)

                // *** End programmer edit section *** (Обслуживание.БилетКасса Set end)
            }
        }
        
        /// <summary>
        /// Обслуживание.
        /// </summary>
        // *** Start programmer edit section *** (Обслуживание.Оператор CustomAttributes)

        // *** End programmer edit section *** (Обслуживание.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual IIS.Kyrs18.Оператор Оператор
        {
            get
            {
                // *** Start programmer edit section *** (Обслуживание.Оператор Get start)

                // *** End programmer edit section *** (Обслуживание.Оператор Get start)
                IIS.Kyrs18.Оператор result = this.fОператор;
                // *** Start programmer edit section *** (Обслуживание.Оператор Get end)

                // *** End programmer edit section *** (Обслуживание.Оператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обслуживание.Оператор Set start)

                // *** End programmer edit section *** (Обслуживание.Оператор Set start)
                this.fОператор = value;
                // *** Start programmer edit section *** (Обслуживание.Оператор Set end)

                // *** End programmer edit section *** (Обслуживание.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбслуживаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбслуживаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбслуживаниеE", typeof(IIS.Kyrs18.Обслуживание));
                }
            }
            
            /// <summary>
            /// "ОбслуживаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбслуживаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбслуживаниеL", typeof(IIS.Kyrs18.Обслуживание));
                }
            }
        }
    }
}
