//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs18
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Покупатель.
    /// </summary>
    // *** Start programmer edit section *** (Покупатель CustomAttributes)

    // *** End programmer edit section *** (Покупатель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупательE", new string[] {
            "ДатРожд as \'Дат рожд\'",
            "ФИО as \'ФИО\'",
            "ID as \'ID\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "ЭлПочта as \'Эл почта\'",
            "БанкСчет as \'Банк счет\'",
            "СерияПаспорта as \'Серия паспорта\'"})]
    [View("ПокупательL", new string[] {
            "ДатРожд as \'Дат рожд\'",
            "ФИО as \'ФИО\'",
            "ID as \'ID\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "ЭлПочта as \'Эл почта\'",
            "БанкСчет as \'Банк счет\'",
            "СерияПаспорта as \'Серия паспорта\'"})]
    public class Покупатель : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатРожд;
        
        private string fФИО;
        
        private int fID;
        
        private int fНомерПаспорта;
        
        private string fЭлПочта;
        
        private int fБанкСчет;
        
        private int fСерияПаспорта;
        
        // *** Start programmer edit section *** (Покупатель CustomMembers)

        // *** End programmer edit section *** (Покупатель CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.ID CustomAttributes)

        // *** End programmer edit section *** (Покупатель.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.ID Get start)

                // *** End programmer edit section *** (Покупатель.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Покупатель.ID Get end)

                // *** End programmer edit section *** (Покупатель.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.ID Set start)

                // *** End programmer edit section *** (Покупатель.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Покупатель.ID Set end)

                // *** End programmer edit section *** (Покупатель.ID Set end)
            }
        }
        
        /// <summary>
        /// БанкСчет.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.БанкСчет CustomAttributes)

        // *** End programmer edit section *** (Покупатель.БанкСчет CustomAttributes)
        public virtual int БанкСчет
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.БанкСчет Get start)

                // *** End programmer edit section *** (Покупатель.БанкСчет Get start)
                int result = this.fБанкСчет;
                // *** Start programmer edit section *** (Покупатель.БанкСчет Get end)

                // *** End programmer edit section *** (Покупатель.БанкСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.БанкСчет Set start)

                // *** End programmer edit section *** (Покупатель.БанкСчет Set start)
                this.fБанкСчет = value;
                // *** Start programmer edit section *** (Покупатель.БанкСчет Set end)

                // *** End programmer edit section *** (Покупатель.БанкСчет Set end)
            }
        }
        
        /// <summary>
        /// ДатРожд.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.ДатРожд CustomAttributes)

        // *** End programmer edit section *** (Покупатель.ДатРожд CustomAttributes)
        public virtual System.DateTime ДатРожд
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.ДатРожд Get start)

                // *** End programmer edit section *** (Покупатель.ДатРожд Get start)
                System.DateTime result = this.fДатРожд;
                // *** Start programmer edit section *** (Покупатель.ДатРожд Get end)

                // *** End programmer edit section *** (Покупатель.ДатРожд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.ДатРожд Set start)

                // *** End programmer edit section *** (Покупатель.ДатРожд Set start)
                this.fДатРожд = value;
                // *** Start programmer edit section *** (Покупатель.ДатРожд Set end)

                // *** End programmer edit section *** (Покупатель.ДатРожд Set end)
            }
        }
        
        /// <summary>
        /// НомерПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.НомерПаспорта CustomAttributes)

        // *** End programmer edit section *** (Покупатель.НомерПаспорта CustomAttributes)
        public virtual int НомерПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.НомерПаспорта Get start)

                // *** End programmer edit section *** (Покупатель.НомерПаспорта Get start)
                int result = this.fНомерПаспорта;
                // *** Start programmer edit section *** (Покупатель.НомерПаспорта Get end)

                // *** End programmer edit section *** (Покупатель.НомерПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.НомерПаспорта Set start)

                // *** End programmer edit section *** (Покупатель.НомерПаспорта Set start)
                this.fНомерПаспорта = value;
                // *** Start programmer edit section *** (Покупатель.НомерПаспорта Set end)

                // *** End programmer edit section *** (Покупатель.НомерПаспорта Set end)
            }
        }
        
        /// <summary>
        /// СерияПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.СерияПаспорта CustomAttributes)

        // *** End programmer edit section *** (Покупатель.СерияПаспорта CustomAttributes)
        public virtual int СерияПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.СерияПаспорта Get start)

                // *** End programmer edit section *** (Покупатель.СерияПаспорта Get start)
                int result = this.fСерияПаспорта;
                // *** Start programmer edit section *** (Покупатель.СерияПаспорта Get end)

                // *** End programmer edit section *** (Покупатель.СерияПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.СерияПаспорта Set start)

                // *** End programmer edit section *** (Покупатель.СерияПаспорта Set start)
                this.fСерияПаспорта = value;
                // *** Start programmer edit section *** (Покупатель.СерияПаспорта Set end)

                // *** End programmer edit section *** (Покупатель.СерияПаспорта Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.ФИО CustomAttributes)

        // *** End programmer edit section *** (Покупатель.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.ФИО Get start)

                // *** End programmer edit section *** (Покупатель.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Покупатель.ФИО Get end)

                // *** End programmer edit section *** (Покупатель.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.ФИО Set start)

                // *** End programmer edit section *** (Покупатель.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Покупатель.ФИО Set end)

                // *** End programmer edit section *** (Покупатель.ФИО Set end)
            }
        }
        
        /// <summary>
        /// ЭлПочта.
        /// </summary>
        // *** Start programmer edit section *** (Покупатель.ЭлПочта CustomAttributes)

        // *** End programmer edit section *** (Покупатель.ЭлПочта CustomAttributes)
        [StrLen(255)]
        public virtual string ЭлПочта
        {
            get
            {
                // *** Start programmer edit section *** (Покупатель.ЭлПочта Get start)

                // *** End programmer edit section *** (Покупатель.ЭлПочта Get start)
                string result = this.fЭлПочта;
                // *** Start programmer edit section *** (Покупатель.ЭлПочта Get end)

                // *** End programmer edit section *** (Покупатель.ЭлПочта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупатель.ЭлПочта Set start)

                // *** End programmer edit section *** (Покупатель.ЭлПочта Set start)
                this.fЭлПочта = value;
                // *** Start programmer edit section *** (Покупатель.ЭлПочта Set end)

                // *** End programmer edit section *** (Покупатель.ЭлПочта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупательE", typeof(IIS.Kyrs18.Покупатель));
                }
            }
            
            /// <summary>
            /// "ПокупательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупательL", typeof(IIS.Kyrs18.Покупатель));
                }
            }
        }
    }
}
